evollu/react-native-fcm

- android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java
Added checking newIntent extras for null onHostResume (I got the error on app start)
> [Android] Checking newIntent extras for null onResume

- README.md
- index.js
no need to include `DeviceEventEmitter` and listen on difficult to write events 😄
> make lib more user friendly

- README.md
Clarify error with onNewIntent #25
> Update readme onNewIntent prototype change

- README.md
updated file name and location
> update Google services info plist format

- ios/RNFIRMesssaging.m
> added registerForRemoteNotifications fixes #44

- README.md
> Add ProGuard information & improve README

- README.md
Very small changes and typo fixes to the `README` file
> Minor changes / typo fix to README

- android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java
- index.js
https://firebase.google.com/docs/cloud-messaging/android/upstream
SenderId can be obtained from google-services.json, but I don't know how to get `R.string.gcm_defaultSenderId` in submodule
> Upstream messages support

- ios/RNFIRMesssaging.m
In conforming with the method signatures as is the case with the
android version, I limited the arguments for `send()` to just
`senderId` and `payload`. This can still be improved upon by adding
`sendDataMessageSuccess` and `sendDataMessageFailure` to events being
fired across the bridge to Js.
> Make upstream messages work on ios

- README.md
This is just to provide a brief usage example and note about sending
upstream messages with `react-native-fcm`
> Upstream example

- ios/RNFIRMessaging.h
- ios/RNFIRMessaging.xcodeproj/project.pbxproj
- ios/RNFIRMesssaging.m
Reverts evollu/react-native-fcm#209
> Revert "Update iOS RN header paths"

- README.md
> Update example project in README

- android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java
Needed a way to show profile pictures in Android notifications. This was my solution.
> Support bitmap urls in large-icon

- README.md
Will save users compilation error
> Specify adding location

- index.js
I set the callback argument because Notification returns undefined.
> Fix FCMEvent.Notification callback argument

- android/build.gradle
Reverts evollu/react-native-fcm#342
> Revert "Upgrade Android build tools to 25.0.1"

- README.md
> Fix editing of AppDelegate.m

- index.d.ts
Minor improvement to the typing declaration.
> Add Notification type

- android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java
by just adding a key called picture to  the notification payload, we can
display image on android notification.
> added big picture style to android notification

- ios/RNFIRMessaging.m
> Fix call to setApplicationIconBadgeNumber

- Examples/simple-fcm-client/app/PushController.js
Thank you for the nice library.
Fixed typo to sample source code.
> Fix type Listner to Listener

- index.d.ts
Related to #509
Based on the README instructions, adds some missing type parameters. 
Looking forward for any feedback.
> Adds some missing parameters on types

- android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java
> Support ongoing notification

- ios/RNFIRMessaging.m
> Added requiresMainQueueSetup as required by newer RN versions

- README.md
Minor change - caught my eye as I was reading the example.
> Updated README syntax

- react-native-fcm.podspec
This Requires cocoapods 1.4 to run
sudo gem install cocoapods --pre
> Fix cocoapods react-native-fcm 11

- android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java
- index.js
- ios/RNFIRMessaging.m
Added missing method for android implementation of android `InstanceId` class.
https://developers.google.com/android/reference/com/google/android/gms/iid/InstanceID
> Add deleteEntityToken and getEntityToken methods

- android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java
> hotfix symbol: variable FirebaseApp

- android/src/main/java/com/evollu/react/fcm/SendNotificationTask.java
Fixes https://github.com/evollu/react-native-fcm/issues/259
> Fix notification grouping

- android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java
- index.js
Added delete notification channel method
> delete notification channel method
