android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java

The signature of `onActivityResult` changed in react-native@0.33, it now passes the Activity as the first parameter.
Tested by making changes locally in an app using react-native@0.33.0-rc.0

Fix build with react-native 0.33

---

.gitignore
ios/RNFIRMessaging.h
ios/RNFIRMessaging.xcodeproj/project.pbxproj

In case someone also decides to use firestack (https://github.com/fullstackreact/react-native-firestack), that comes prepackaged with most of the Firebase libraries.  This PR just adds the Firestack directories to the search paths so that if they have this set up it'll pick up the frameworks from there.  It shouldn't affect things if you still want to install the frameworks via cocoapods as those paths are still there.

Firestack compatibility

---

android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java

If application activity is singleTop and minimized/restored from launcher icon -- in that case activity is reused and intent.getExtras() returns null.

Prevent NullPointerException in onNewIntent

---

README.md

* Fix iOS 10 specific documentation
* Fix typos/spelling-errors
I found additional `+ +` probably from a diff in iOS 10 doc, so decided to fix a few typos as well :-)

Fix README for iOS 10 docs

---

README.md
android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java

It would be possible to customize even more the parameters of the LED blinking using [setLights](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#setLights(int, int, int)) but I was happy with the default one.

Add basic LED blinking support for local notifications on Android

---

android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java

Android notification + data push notifications when the app is in the foreground only passes the data packet through, this changes it to pass the notification data too

Add FCM notification details to the foreground notification

---

README.md

I was having build problems and was not able to use the underlying `FIRMessaging` object until I made this change. I think adding this in the README in the actual setup will help folks avoid this problem in the future.

Additional steps to edit MainApplicaiton .java

---

ios/RNFIRMessaging.h
ios/RNFIRMessaging.xcodeproj/project.pbxproj
ios/RNFIRMesssaging.m

https://github.com/facebook/react-native/commit/e1577df1fd70049ce7f288f91f6e2b18d512ff4d moves header imports to `<React/*>`. This updates header include path and all imports so build works against react master (soon to be version 0.40.0).

Update iOS RN header paths

---

README.md

In the README, there is an extra `+` that causes XCode build to fail with the error: `undeclared identifier userInfo`.
Resolves #205

Fixed typo that caused XCode error: undeclared identifier userInfo

---

.gitignore
android/build.gradle
android/src/main/java/com/evollu/react/fcm/BadgeHelper.java
android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java
android/src/main/java/com/evollu/react/fcm/MessagingService.java

Using Leolin's ShortcutBadger we are able to support any badge counts that are sent as part of the notifications data-payload.

feature(android): add support for badge count

---

react-native-fcm.podspec

This enables us who like using cocoapods instead of the manual hassle of integrating RN libs to import the project by adding
```
pod 'react-native-fcm',  path: '../node_modules/react-native-fcm'
```
to the Podfile

Support install from podfile

---

ios/RNFIRMesssaging.m

Error:
```objc
Assertion failure in -[GIPReachability startWithCompletionHandler:]
'NSInternalInconsistencyException', reason: 'GIPReachability should be used from the main thread'
```
Fixes #233

Fix iOS crash on startup due to wrong thread

---

ios/RNFIRMessaging.h
ios/RNFIRMesssaging.m

I use installation with cocoapods. And I have problems with modules import. But import of headers works. Suddenly I can't explain that. This error I've got.
`app/node_modules/react-native-fcm/ios/RNFIRMessaging.h:4:9: Module 'FirebaseCore' not found`. I can provide simple project which shows that bug.
**One small note about cocoapods**: I can't use `use_frameworks` because one of my dependency doesn't work with it and https://github.com/facebook/react-native/issues/11781 react also is not compiling with it.

attempt to fix installation with cocoapods

---

Examples/simple-fcm-client/app/FirebaseConstants.js
Examples/simple-fcm-client/app/PushController.js

I found an issue while investigating issue #343 where Platform is not imported from 'react-native' so I imported and added a base FirebaseConstants file for those new to ES6 syntax and React-Native.

Fixed Platform not being imported and added a base for FirebaseConstants

---

android/build.gradle

This is generally a good idea. I did it specifically because the latest [Android Gradle plugin 2.3.0](https://developer.android.com/studio/releases/gradle-plugin.html) only supports build tools versions >=25.

Upgrade Android build tools to 25.0.1

---

android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java

Exception after FCM.scheduleLocalNotification call:
```
Key fire_date expected Long but value was a java.lang.Double.  The default value 1489824292000 was returned.
Attempt to cast generated internal exception:
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
at android.os.BaseBundle.getLong(BaseBundle.java:834)
at com.evollu.react.fcm.FIRLocalMessagingHelper.sendNotificationScheduled(FIRLocalMessagingHelper.java:224)
at com.evollu.react.fcm.FIRMessagingModule.scheduleLocalNotification(FIRMessagingModule.java:86)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:345)
at …
```

Fix of "Key fire_date expected Long but value was a java.lang.Double" exception

---

README.md

We were using v2.5.6 and it's definitely required for that version. (It's mentioned briefly in non-cocoapods instructions, but we did cocoa pods and missed it!).
Not sure if later versions don't require this step?

Added missing push notifications step

---

README.md

Update README to remove the line that says to uncomment the "use_frameworks!" line as it is not required anymore.

Do no require "use_frameworks!" the podfile

---

Examples/simple-fcm-client/app/App.js

I believe nobody wants to manually type the lengthy token, so now Users of the Example app can copy the token to clipboard simply by pressing on the token. A feedback message is displayed when the User presses on the token text, indicating the token was copied to the clipboard (so it is a hidden feature but easily found by frustrated Users).

Added copy-to-clipboard feature for token

---

README.md

When I first configured react-native-fcm I missed the compile project(':react-native-fcm') line because it's not stated as change in the diff viewer. corrected this

Update READ.ME with correct diff for dependencies

---

android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java

When the app is opened with a notification Intent, the notification contains 'collapse_key', 'google.message_id', 'google.sent_time', 'from'.
When a notification is received while the app is in the foreground, these fields are missing.
This PR adds these fields for the foreground notifications.

Provide collapse_key, from, mesage_id, and send_time in foreground notificaitons

---

README.md

Updates the "notes" section in the README to recommend staying on the iOS SDK v3.
Temporary workaround for https://github.com/evollu/react-native-fcm/issues/422; this PR is not necessary if https://github.com/evollu/react-native-fcm/pull/421 is merged right away, assuming that's the only fix necessary.

Recommend staying on iOS SDK v3

---

android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java

Just return the `className` instead of trying to get the `Class`. The old code didn't work with [activity aliases](https://developer.android.com/guide/topics/manifest/activity-alias-element.html).
For example, when launching the app with `<activity-alias android:name=".AliasActivity" android:targetActivity=".MainActivity" />`, the old code would try to get the class for `AliasActivity` which threw `ClassNotFoundException`.
The exception is avoided if we simply pass the aliased `className` to the new `Intent`.
Tested/verified on a physical device and the example app with local and remote notifications :)

Support Android activity aliases

---

README.md
android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java
index.js
ios/RNFIRMessaging.h
ios/RNFIRMessaging.m

Created function to delete instanceId from both Android and iOS so that new FCM Token can be generated and the old token can be revoked

Delete instanceId function

---

android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java

`FirebaseInstanceId.getInstance()` can throw exceptions. For example if Firebase was not initialized.

safe FirebaseInstanceId.getInstance() access.

---

ios/RNFIRMessaging.m

Fix typo so 'grant' is spelled correctly

---

android/src/main/java/com/evollu/react/fcm/FIRMessagingPackage.java

Since of recently in master the unused createJSModules has been removed and ReactPackage's no longer contain the definition of createJSModules. There for it must be removed in order to not yield a compile error. This is breaking change.
https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

Remove override of createJSModules

---

README.md

Running `pod install Firebase/Messaging` results in `[!] Unknown command: 'Firebase/Messaging'` using Cocoapods v1.3.1.
Also, there was a parse error in `HEADER_SEARCH_PATHS = "$(SRCROOT)/../node_modules/react-native/Libraries/PushNotificationIOS/**""$(SRCROOT)/../node_modules/react-native-fcm/ios";`, I was able to fix it by opening `APPNAME.xcodeproj/project.pbxproj`.

Fix pod installation syntax

---

android/src/main/java/com/evollu/react/fcm/FIRLocalMessagingHelper.java
ios/RNFIRMessaging.m

This causes the local notification to have the same behavior as the automatic Firebase notification: If the `sound` property is not set, the notification is muted.
If `default` value is set, the default sound is still considered.
Please let me know if anything else needs to be changed.
Custom sound:
```js
FCM.presentLocalNotification({
id: ...                       
title: ...,                               
body: ...,                                                            
sound: "my-custom-sound",
priority: ..., 
click_action: ...,   
my_custom_data: ...,
});
```
Default sound:
```js
FCM.presentLocalNotification({
id: ...                       
title: ...,                               
body: ...,                                                            
sound: "default", …
```

Allow local notification without sound (Android and iOS)

---

android/src/main/java/com/evollu/react/fcm/FIRMessagingPackage.java
ios/RNFIRMessaging.m

to fix issue #510
according to Apple's document, apns device token is a bytes array in DSData. It cannot be converted into NSString with NSUTF8StringEncoding which is RN's default but requires a special converting method.

fix getAPNSToken returning (null)

---

ios/RNFIRMessaging.m

Xcode 9 introduced Main Thread Checker, which detects UI API calls on non-UI threads and can be enabled for debug builds.  It ends up complaining about the invocation of `registerForRemoteNotifications()` on a background thread.  This patch fixes the warnings.
https://stackoverflow.com/questions/44391367/swift-4-uiapplication-registerforremotenotifications-must-be-called-from-mai

Dispatch registerForRemoteNotifications on main thread to prevent runtime warnings 

---

ios/RNFIRMessaging.m

Adding a couple of missing break statements that prevents unitFlags taking the default value when the repeat_interval is month and year. Aso removes a couple of dead code warnings in Xcode.

Fix switch cases for all NSCalendarUnits

---

README.md

Only a few changes.
> Edit android/app/build.gradle. Add at the bottom of the file:
But this example did not look like.
```diff
dependencies {
classpath 'com.android.tools.build:gradle:2.0.0'
+   classpath 'com.google.gms:google-services:3.0.0'
```

Update README about Android Configuration

---

android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java
index.js

Fixes two bugs in the sdk-26 branch: Double resolution of the channel-creation promise and failure to pass options from JS to native

Bugfixes for sdk-26 branch

---

ios/RNFIRMessaging.m

This patch prevents the following runtime warnings.
```
2018-01-28 02:58:45.501473+0900 *************[368:47835] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication setApplicationIconBadgeNumber:]
PID: 368, TID: 47835, Thread name: (none), Queue name: com.facebook.react.RNFIRMessagingQueue, QoS: 0
Backtrace:
4   *************                       0x00000001010de294 -[RNFIRMessaging setBadgeNumber:] + 68
5   CoreFoundation                      0x0000000182691cd0 <redacted> + 144
6   CoreFoundation                      0x000000018257056c <redacted> + 292
7   CoreFoundation                      0x000000018257501c <redacted> + 60
8   *************                       0x0000000100ee2528 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2064
9 …
```

Dispatch setApplicationIconBadgeNumber on main thread to prevent runtime warnings

---

ios/RNFIRMessaging.xcodeproj/project.pbxproj

By adding the pod paths, we ensure that if dependencies (namely React) are installed *only* via Pod and not via direct linking in the project.

Add Pod paths to header search paths

---

README.md
index.d.ts
index.js
ios/RNFIRMessaging.m

This PR adds support for notification actions on iOS as documented [here](https://goo.gl/7avC8b) by Apple.
| NotificationActionType.Default | NotificationActionType.TextInput |
| --- | --- |
| ![2016-12-02_07-58-59](https://user-images.githubusercontent.com/250009/35787681-39a8110c-0a30-11e8-95b5-103104cd6af2.png) | ![2016-12-02_07-59-20](https://user-images.githubusercontent.com/250009/35787708-6ee63ede-0a30-11e8-80f3-e9397b774a55.png)|
resolves #325

Add support for notification actions on iOS

---

ios/RNFIRMessaging.m

Simulator not return deviceToken, deviceToken only return in device with valid APNS certificate
`tokenWithAuthorizedEntity` with no deviceToken will crush

Fix iOS simulator getEnitityToken

---

android/src/main/java/com/evollu/react/fcm/SendNotificationTask.java

Added action buttons generating on Android (iOS-way was described in the [issue](https://github.com/evollu/react-native-fcm/issues/325)).
Read the `actions` field in the `custom_notification` object in a remote notification:
```
{
"to" : "some_token",
"data" : {
"custom_notification": {
"actions": "Call, Reject",
"color":"#00ACD4",
"priority":"max"
}
}
}
```
So the result should be a notification with two buttons named `Call`, `Reject`.
When we press the button the `notification` body will contain the `_actionIdentifier` with pointed button name, so we can identify what button was pressed. For example, if we press `Call`, the `_actionIdentifier` also will be `Call`.

Android actions

---

android/src/main/java/com/evollu/react/fcm/SendNotificationTask.java

- Changed `IntentClass` => `IntentClassName`.
- Added ability to send `android_actions` as an array, for example:
```
{
"to" : "fcm_token",
"data" : {
"custom_notification": {
"android_actions": ["First action", "Second action"],
"color":"#00ACD4",
"priority":"max"
}
}
}
```
- As `android_actions` is an `ArrayList` so the bundle can't correctly be parsed, I have added `bundle.remove("android_actions");` to avoid any parsing errors (we will not use this field further so it is unnecessary). Any workarounds for this or it's OK?

Android actions fixes #1

---

android/src/main/java/com/evollu/react/fcm/SendNotificationTask.java

In my case, when I'm trying to send a notification with `android_actions` payload, the app crashes because it tries to find the icon.
```
couldn't inflate view for notification com.myapp/0x2e37b245
android.content.res.Resources$NotFoundException: Resource ID #0x1
at android.content.res.Resources.getValue(Resources.java:2452)
at android.content.res.Resources.getDrawable(Resources.java:1947)
at android.content.Context.getDrawable(Context.java:409)
```
And then:
```
FATAL EXCEPTION: main
Process: com.myapp, PID: 18384
android.app.RemoteServiceException: Bad notification 
posted from package com.myapp: Couldn't expand RemoteViews for: 
StatusBarNotification(pkg=com.myapp user=UserHandle{0} id=775402053 tag=null score=20 
key=0|com.myapp|775402053|null|10278: Notification(pri=2 …
```

Remove icon from addAction

---

android/build.gradle

A better fix for Google Play Services taking project properties

---

android/src/main/java/com/evollu/react/fcm/SendNotificationTask.java

This is needed when the strings are encoded in utf8. The encoding is needed for special characters (as simple as é) and smileys. 
In my use case, I only need title, body and big_text (not familiar with the new additions: action, etc.) but any string in the notification could need decoding. 
String X = bundle.getString("X")
X= URLDecoder.decode( X, "UTF-8" );
If there is interest in the PR, I will apply the decoding to all strings in the bundle.
Medium term, it could be nice to have a tag for encoding in the initial message that would trigger or not a decoding.

Decode utf-8 before presentation

---

README.md

True story :P
Thank you for the library!

Updated Q&A

---

Examples/simple-fcm-client/android/app/build.gradle

1. Move the google-services plugin to the bottom to avoid a building time error
2. Error message: app:processDebugGoogleServices FAILED

Fixed processDebugGoogleServices building error

---

android/src/main/java/com/evollu/react/fcm/FIRMessagingModule.java

when native functions throw exceptions, app won't crash

Safe FirebaseMessaging usage

---

android/build.gradle

Bump Android build tools version to 28.x and support-core-utils to 28.0.0.
This PR fixes a bug:
`Could not find com.android.support:support-core-utils:27.1.1`
It seems that `support-core-utils` 27.1.1 is not on maven anymore. Bumping to 28.0.0 fixed it.
when I use it with `react-native-fast-image`. Anyway the dependencies should be upgraded, as 28.0.0 stable is released.

Bump Android version

---

ios/RNFIRMessaging.m

The latest updates of Firebase/Messaging use a new method as a requirement of the FIRMessagingDelegate for iOS. This PR includes that method in addition to the old one.

Fix FIRMessagingDelegate requirements
